# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/jeremias/.zshrc'

autoload -Uz promptinit
promptinit

autoload -Uz compinit
compinit

export PATH="$(yarn global bin):$PATH"

# End of lines added by compinstall
